### ISSUE TITLE
API

### ISSUE THREAD

**Issue by rajan-magar** [bc67da8d/corona-smart-tracker-data#1]
Its really cool project can you make an API for this same?

**Comment by caovanthanh203** [comment]
I don't share API because you can use raw link of github file as API endpoint well, which can serve a ton of requests per second:
https://raw.githubusercontent.com/bc67da8d/corona-smart-tracker-data/master/case.json
https://raw.githubusercontent.com/bc67da8d/corona-smart-tracker-data/master/map.json
https://raw.githubusercontent.com/bc67da8d/corona-smart-tracker-data/master/chart.json

If you can not use it, you can use my API at:
http://corona.hamatim.com:3000/case-report
http://corona.hamatim.com:3000/map-report
http://corona.hamatim.com:3000/chart-report
